Fix concourse pipeline (#5)
* fix forgotten rename in pipeline

* change and push to trigger PR check

* tidy up concourse code and trigger pr check

* more readme to trigger pr check

* trigger pr when modifying readme

* update pipeline

* fix gha actions

* fixing credentials from 30 imnutes to 8 hours

* fix silly typo

* fix message

* PR changes

Co-authored-by: WW Teo <whay-wang.teo@engineering.digital.dwp.gov.uk>

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -14,7 +14,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Build Docker image
-        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
+        run: docker build -t ${{ env.IMAGE_NAME }}:latest . -q >/dev/null 2>&1 || echo "Build Failed"
         working-directory: build
 
   test:
